### ISSUE TITLE
Password Confirmation functionality for Registration

### ISSUE THREAD

**Issue by Anjalizi** [anitab-org/mentorship-backend#252] opened 2019-12-05 10:14 UTC
Whenever a user registers on the mentorship portal, he/she should enter the desired password and confirm the same before registering.

**Describe the solution you'd like**
Two password input fields should be present: password and confirm_password on POST/register API on the mentorship-backend

**Comment by isabelcosta** [comment] 2019-12-10 23:05
Interesting @Anjalizi 🤔Thank you for creating this issue to start a discussion on this :)

My concern here is that this was implemented like this by design. When we were discussing this during the Google Summer of Code program, we (me and the mentors) decided that this verification should be done on the frontend app (whether is mobile or web)
So:
- in the Android application we have the this implemented, in the sense the on the registration screen the password has to be input 2 times (the comparison logic is put there).
- If we create a web application, this password confirmation feature would happen there as well.
- Also for the change password API, it works the same way as in here. The validation works at the frontend level.

What do you think @Anjalizi ?
cc @systers/maintainers-mentorship-backend

**Comment by Anjalizi** [comment] 2019-12-11 06:32
You are right @isabelcosta. Putting the confirmation logic on the backend only puts unnecessary load on the server when the same can easily be done on the frontend.

**Comment by isabelcosta** [comment] 2019-12-11 22:30
@Anjalizi I'm glad you understood out point :D and also because you brought this up through an issue, now this is publicly documented 🎉

**Comment by isabelcosta** [comment] 2019-12-11 22:32
I will close this issue, since we're both agree that this would not be necessary :)

**Comment by isabelcosta** [comment] 2019-12-12 17:20
this is being used for GCI, so I will re open this for the duration of the program

**Comment by isabelcosta** [comment] 2020-02-12 10:04
Closing this, since GCI contest is over.

**Closed as completed by isabelcosta** 2020-02-12 10:04 UTC
