### ISSUE TITLE
Actual response message & Status code and that stated in the Responses section don't match

### ISSUE THREAD

**Issue by surbhigoel191** [anitab-org/mentorship-backend#958] opened 2021-01-04 17:36 UTC
**Describe the bug**

While creating user, if the username/password are too short (let's say 2 characters), the actual response will show different min. limit from min. limit stated in the Responses section and Conflict status code while it is documented as Bad_Request. And in case the name is short, that error is not even listed in the Responses but shown in the actual response.

**To Reproduce**

1. Go to User
2. Scroll down to /register (Creates a new user)
3. Enter short username/password/name.
4. Click on execute.
5. Scroll down to response.
6. Match the response to the documented ones.
7. See error.

**Expected behavior**
The actual errors should be documented in the Responses section.

**Screenshots**

![Screenshot (254)](https://user-images.githubusercontent.com/44471561/103562396-0a290280-4ee1-11eb-9565-af2a1842e009.png)
![Screenshot (255)](https://user-images.githubusercontent.com/44471561/103562402-0c8b5c80-4ee1-11eb-9dfa-8682d60cf19e.png)
![Screenshot (253)](https://user-images.githubusercontent.com/44471561/103562404-0c8b5c80-4ee1-11eb-9955-d2c3efd7316c.png)

**Comment by sankha555** [comment] 2021-01-05 18:32
Hello @surbhigoel191,
I think I have found out the code fragment due to which this inconsistency is arising and would like to fix it. Can you please assign this issue to me? 

Also, the running the server on "local" mode doesn't produce exactly this page (eg. there is not HTTPStatus.CONFLICT and their corresponding messages in the description in responses, it only has the code status like 200 and 400). Can you please tell me how to reproduce this exact UI as in the deployed app on heroku so that I can test my patch? Thanks!

**Comment by vj-codes** [comment] 2021-01-06 07:37
@surbhigoel191 thank you for creating this issue , however this is a duplicate of issue #653 so I will be closing it now to avoid conflicts .
@sankha555 you can go through other available issues for your contributions :)

**Closed as completed by vj-codes** 2021-01-06 07:37 UTC
