### ISSUE TITLE
Fix Missing Punctuations in Messages.py

### ISSUE THREAD

**Issue by sara-02** [anitab-org/mentorship-backend#248] opened 2019-12-03 19:23 UTC
**Describe the bug**
The `messages.py` has a few inconsistent punctuations with either missing periods in some places and misplaced periods in others.  We want to bring some consistency in the messages we report to the user, by fixing these.

**Lines with missing period**

1. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L4
2. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L24
3. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L42
4. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L76
5. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L76
6. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L202
7. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L204
8. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L208
9. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L209

**Lines with misplaced period**
1. https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L40

**Expected result**
All the above typos to be fixed in the `messages.py` as a single commit.

**Estimated time**
1 hour

**Comment by alexanderwlee** [comment] 2020-01-09 07:52
Hi! I'm just starting out with contributing to open source, and I would love to work on this!

**Comment by sara-02** [comment] 2020-01-10 20:12
Hello, @alexlee311 welcome to Systers and welcome to open source. As you can see the task is currently labelled `Program: GCI` which means it can be used during the contest by the participants. If you are participating in GCI feel free to work on it. Else you will have to wait until 21st Jan to work on this task. I suggest you can pick some tasks not labelled GCI for the time being.

**Comment by alexanderwlee** [comment] 2020-01-12 09:37
Thanks for the reply @sara-02! Sorry about the confusion. I will find another task!

**Comment by isabelcosta** [comment] 2020-01-12 17:17
@alexlee311 i would also encourage, if you see anything that can be improved in the app, even if a small change let us know by creating an issue or even creating PR if the change is really small

**Comment by alexanderwlee** [comment] 2020-01-13 12:56
sounds good, thanks! @isabelcosta

**Comment by StergiosSozos** [comment] 2020-03-12 12:48
Hello!
This is my first time contributing to an open source project. In order to get familiar with the procedure can i additionaly take this issue?

**Comment by isabelcosta** [comment] 2020-03-12 22:05
I think you are already assigned to an issue right @StergiosSozos ? If yes, then please finish that work first if not, let me know and I can assign this to you

**Comment by ibLeDy** [comment] 2020-03-14 13:33
Hi, i would love to work on this issue!

**Comment by isabelcosta** [comment] 2020-03-14 14:26
@StergiosSozos since you already are assigned to one issue, I won't consider you to work on this issue.
@alexlee311 are you still interested in working on this issue since the GCI contest is over now?
@ibLeDy if we don't get an answer from @alexlee311 during this weekend, then let me know so I can assign this to you.

**Comment by isabelcosta** [comment] 2020-03-15 14:36
@ibLeDy I will assign this to you :)

**Comment by ibLeDy** [comment] 2020-03-15 17:35
Thank you!

I see that the issue is a bit old and some of the lines mentioned now have periods ([L42](https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L42)) and i think i remember seeing one that was not listed when i first looked at the issue, so looking at the entire file would be good, just in case. 

*Edit: i see that a formatter was used so maybe the line numbers don't match with the original issue*

~~About the [misplaced one (L40)](https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L40), where is it supposed to be? As i currently see it where others are placed, i am not familiar with this repo so i don't want to make any assumption :)~~

**Closed as completed** 2020-03-16 20:59 UTC
Labels: Category: Coding, Type: Enhancement, First Timers Only
