### ISSUE TITLE
Use HTTPStatus instead of hard coded status codes in resources/mentorship_relation.py file

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#846] opened 2020-09-08 09:22 UTC
**Describe the bug**
[mentorship_relation](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/mentorship_relation.py) file has **few routes** that uses hardcoded status codes instead of HTTPStatus.

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Click on `Mentorship Relation`
3. Scroll down to `/mentorship_relation/{request_id}`

**Expected behavior**
HTTPStatus.XYZ should have been displayed instad of raw status codes

**Screenshots**
![image](https://user-images.githubusercontent.com/42068010/92457517-f0e9a100-f1e1-11ea-8b87-dfe1493feb56.png)
The above image shows hardcoded status codes. It should show the status in the below format:-
![image](https://user-images.githubusercontent.com/42068010/92457900-66ee0800-f1e2-11ea-88c5-b341b8cfb31b.png)

**Additional Context**
Also, find whether any such hard coded status codes are used for other routes and fix them.

**Comment by sreelekha901** [comment] 2020-09-08 13:13
Can I work on this issue?

**Comment by abhinav72610** [comment] 2020-09-08 14:04
currently i have no issue assigned...i would like to work on this

**Comment by rutujadhanawade** [comment] 2020-09-08 14:19
I would like to work on this

**Comment by yash2189** [comment] 2020-09-08 18:36
Can I work on this?

**Comment by SanketDG** [comment] 2020-09-08 18:40
Assigning @sreelekha901 since she is not assigned to any issue and asked first.

**Comment by sreelekha901** [comment] 2020-09-10 06:20
I need some help to proceed with this issue

**Comment by PrashanthPuneriya** [comment] 2020-09-10 07:38
What do you need help with @sreelekha901 ?

**Comment by devkapilbansal** [comment] 2020-11-11 20:31
@PrashanthPuneriya can you please update the issue title and description to fix all hard coded status codes instead of mentorship_relation file

**Comment by Aaishpra** [comment] 2020-12-22 07:14
@PrashanthPuneriya @isabelcosta can I take this up?

**Comment by devkapilbansal** [comment] 2020-12-22 12:14
I don't think that this issue is valid anymore. Can you please reproduce it first @Aaishpra ?

**Comment by isabelcosta** [comment] 2020-12-22 12:56
Just a comment, actually, the value being shown on Swagger UI should be in number format: so 200 instead of `HTTPStatus.OK`. In the code it should use the `HTTPStatus` enum, but it should show the real number in the Swagger UI. I think this issue is not about that, but it is instead about if is there numbers hardcoded in the code (instead of enums). so this should still be checked how @devkapilbansal said. Thank you for coming with this @devkapilbansal 

We should additionally have an issue to make sure the SwaggerUI shows the values and not the enum representation. that is an implementation detail. the solution might be something like using `str(HTTPStatus.OK)` or `HTTPStatus.OK.value`, not sure 🤔

**Comment by Aaishpra** [comment] 2020-12-22 14:26
@devkapilbansal you are right this issue is not valid anymore, I reproduced it in the Heroku app and the status codes are displayed correctly for mentorship relations, #924 already solved it.

**Comment by Aaishpra** [comment] 2020-12-22 15:34
> Just a comment, actually, the value being shown on Swagger UI should be in number format: so 200 instead of `HTTPStatus.OK`. In the code it should use the `HTTPStatus` enum, but it should show the real number in the Swagger UI. I think this issue is not about that, but it is instead about if is there numbers hardcoded in the code (instead of enums). so this should still be checked how @devkapilbansal said. Thank you for coming with this @devkapilbansal
> 
> We should additionally have an issue to make sure the SwaggerUI shows the values and not the enum representation. that is an implementation detail. the solution might be something like using `str(HTTPStatus.OK)` or `HTTPStatus.OK.value`, not sure thinking

@isabelcosta @devkapilbansal shall I open the issue and work on it  according to as @isabelcosta suggested.

**Comment by isabelcosta** [comment] 2020-12-22 19:42
Ok so if this is not valid anymore I will close this @devkapilbansal @Aaishpra 

@Aaishpra yes, you can create the issue for it and work on it :) Try to create an issue for a module of the code. For example, you can create an issue to do what I mentioned for Admin API or Mentorship Relation API or User API. So that the file changes in the code review are "small" and easier to review. Makes sense?

You can start with an issue for showing the values on Admin API, and then if the others are still available you continue those. Just let me know once you create the issue so we can assign it to you :)

**Closed as completed** 2020-12-22 19:43 UTC
Labels: Category: Coding, First Timers Only

**Comment by Aaishpra** [comment] 2020-12-23 06:20
> Ok so if this is not valid anymore I will close this @devkapilbansal @Aaishpra
> 
> @Aaishpra yes, you can create the issue for it and work on it :) Try to create an issue for a module of the code. For example, you can create an issue to do what I mentioned for Admin API or Mentorship Relation API or User API. So that the file changes in the code review are "small" and easier to review. Makes sense?
> 
> You can start with an issue for showing the values on Admin API, and then if the others are still available you continue those. Just let me know once you create the issue so we can assign it to you :)

Thanks, @isabelcosta  got your point will create an issue for the mentorship_relation Api first and work on it and after that we can  create more for the remaining APIs.
