### ISSUE TITLE
Create a reporting_guidelines.md

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/mentorship-backend#772] opened 2020-08-28 18:42 UTC
## Description
As a user, I need to modify the reporting guidelines, so that I can seek for help when necessary.
1. The content should be consistent with [Reporting Guidelines](https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/reporting_guidelines.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section.
3. Add the updated Reporting Guidelines file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020.

**Comment by atharwa-24** [comment] 2020-08-28 20:37
I would like to work on this!!!

**Comment by rutujadhanawade** [comment] 2020-08-29 06:43
I would like to work on this

**Comment by niyati-n** [comment] 2020-08-29 12:13
i would like to work on this

**Comment by sanchibansal340** [comment] 2020-08-29 12:38
Comment on 1st September and I will assign it to you.

**Comment by Abjcodes** [comment] 2020-08-31 18:39
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by bhumikasharma29** [comment] 2020-08-31 18:41
I would like to work on this issue. Please assign it to me.

**Comment by Hyper-Matrix** [comment] 2020-08-31 18:46
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by atharwa-24** [comment] 2020-08-31 18:53
Would like to work on this one~ OSH

**Comment by sanchibansal340** [comment] 2020-09-01 05:09
@Hyper-Matrix I am assigning this to you.

**Comment by 96RadhikaJadhav** [comment] 2020-09-01 12:53
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by atharwa-24** [comment] 2020-09-01 19:13
if the issue is not assigned yet i will like to get assigned!

**Comment by heyanurag** [comment] 2020-09-02 06:54
Can I work on this issue? I am a first time contributor.

**Comment by anishghimire603** [comment] 2020-09-02 07:55
@sanchibansal340  Will you assign me this issue please?

**Comment by heyanurag** [comment] 2020-09-02 07:57
I would still like to try this.

**Comment by Tushika25** [comment] 2020-09-02 08:56
I would like to work on this issue. Thank You!!!

**Comment by sujal111** [comment] 2020-09-08 12:48
I am willing to work and solve this issue. Please assign me the same

**Comment by vj-codes** [comment] 2020-09-08 19:23
@Hyper-Matrix how's the PR going? Do update after every 3 days incase it's taking long otherwise issue will be assigned to person next

**Comment by sanchibansal340** [comment] 2020-09-09 20:07
@atharwa-24 Would you like to work on this issue?

**Comment by rutujadhanawade** [comment] 2020-09-10 03:04
I would like to work on this issue.

**Comment by dadheech-vartika** [comment] 2020-09-10 13:29
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by sanchibansal340** [comment] 2020-09-10 13:51
@96RadhikaJadhav would you like to work on this issue?

**Comment by atharwa-24** [comment] 2020-09-10 14:32
I would like to work @sanchibansal340

**Comment by atharwa-24** [comment] 2020-09-10 14:33
if its not assigned to anyone yet

**Comment by sanchibansal340** [comment] 2020-09-10 14:33
Okay I am assigning it to you @atharwa-24

**Closed as completed** 2021-01-24 02:59 UTC
Labels: Category: Documentation/Training, Type: Maintenance, First Timers Only
