### ISSUE TITLE
Perform manual testing and report GET /user/confirm_email/{token} API

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#870] opened 2020-09-15 13:14 UTC
## Description

As a tester,
I need to test GET /user/confirm_email/{token} API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#confirmation-of-users-email](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#confirmation-of-users-email)

### Update [Required]
- [ ] Test GET /user/confirm_email/{token} API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by vj-codes** [comment] 2020-09-15 15:19
@gaurivn hey I would like to work on this

**Comment by gaurivn** [comment] 2020-09-15 15:55
Here you go

**Comment by vj-codes** [comment] 2020-09-16 20:32
@gaurivn I kinda have a doubt - in this screen shot is the part after
 `https://mentorship-backend-temp.herokuapp.com/user/confirm_email/` the token sent to user ? or the token is something else
![image](https://user-images.githubusercontent.com/60894542/93389105-4deff180-f889-11ea-8b47-ffa0d201bee8.png)

**Comment by vj-codes** [comment] 2020-09-17 09:43
@mtreacy002 any idea ^^^

**Comment by vj-codes** [comment] 2020-09-18 17:34
Removing my assignment as it was discussed on zulip hat this api is not something that a user can manually test .The token is generated internally . If you  @gaurivn can clarify more about this issue , I will like to work on this later.Thanks!

**Comment by codesankalp** [comment] 2020-09-22 17:00
@gaurivn I would like to work on this issue.

**Comment by isabelcosta** [comment] 2020-09-22 18:36
My clarification from Zulip:

@**Maya Treacy - GSoC20 Student - Volunteer** I think this can still be tests. Even though we know this is not directly used by frontend, someone could still try to use the API is wrong ways (I am imagining a hacker scenario for example), we don't want someone to manage to use the API and temper with data. for example the code could have a bug and allow for POST requests on that endpoint. We want too make sure that the responses are predictable. For example, what if I don't provide a token, what should happen?

- GET https://mentorship-backend-temp.herokuapp.com/user/confirm_email/<fake_token>
- POST https://mentorship-backend-temp.herokuapp.com/user/confirm_email/<real_token>

Here's an example of me testing on Postman:

![image](https://user-images.githubusercontent.com/11148726/93923071-c6800380-fd0a-11ea-9970-02d5e17962da.png)

So this might not be a priority, but it can be relevant :) Does this make sense? 
@mtreacy002 @vj-codes

**Comment by isabelcosta** [comment] 2020-09-22 18:36
@codesankalp since @vj-codes is working on other issues, I will assign this one to you :)
Happy Coding!

**Comment by codesankalp** [comment] 2020-09-23 09:02
Thanks, @isabelcosta for assigning me this issue I will soon make a pr related to testing this API.

**Comment by codesankalp** [comment] 2020-09-23 11:25
@isabelcosta @gaurivn 
you can review this pull request. Thanks :smiley:

**Comment by codesankalp** [comment] 2020-09-24 05:53
### Details of what i did in the test.
* Test 1 : Verification token entered is one sent on user's registered email within 24 hrs

     _Screenshot/gif_: 
     
     ![test_1](https://user-images.githubusercontent.com/56037184/94105745-91cd9280-fe57-11ea-90e7-6e514cb3ada2.png)


     _Expected Result_: SUCCESS (message: You have confirmed your account. Thanks!)

     _Actual Result_: SUCCESS (message: You have confirmed your account. Thanks!)


* Test 2:  Verification token of already confirmed users account entered

     _Screenshot/gif_: 
     
     ![test_2](https://user-images.githubusercontent.com/56037184/94105790-a90c8000-fe57-11ea-8044-aee26039567e.png)


     _Expected Result_:  SUCCESS (message: Account already confirmed)

     _Actual Result_: SUCCESS (message: Account already confirmed)


* Test 3:  Verification token of un-confirmed users account entered after 24 hrs of email being sent

     _Screenshot/gif_: 
     
    ![test_3](https://user-images.githubusercontent.com/56037184/94105821-bf1a4080-fe57-11ea-9f9f-2d895a62fffb.png)


     _Expected Result_:  Failure (message: The confirmation link is invalid or the token has expired.)

     _Actual Result_: SUCCESS (message: You have confirmed your account. Thanks!)

    _Reason_: I tested it and it is valid for 30days.


* Test 4:  Incorrect verification token entered in request body

     _Screenshot/gif_: 
     
    ![test_4](https://user-images.githubusercontent.com/56037184/94105890-e83ad100-fe57-11ea-92c9-95951ae57bb1.png)


     _Expected Result_:  Failure (message: The confirmation link is invalid or the token has expired.)

     _Actual Result_: FAILURE (message: The confirmation link is invalid or the token has expired.)

**Closed as completed** 2020-11-19 23:53 UTC
Labels: Category: Documentation/Training, Category: Quality Assurance
