### ISSUE TITLE
Bug: Dev server GET all users 503 error response

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#571] opened 2020-05-05 00:11 UTC
When I tried to get list of all users on the dev server, it returned 503 error response 'Service Unavailable'. This doesn't happen when the same request is done on the local server.

**To Reproduce**

1. Go to dev server Swagger UI https://mentorship-backend-temp.herokuapp.com.
2. Login and get the access token.
3. Scroll down to GET users and use the token to get users list.

**Expected behavior**
This request should return list of users.

**Screenshots**
error response on dev server:
<img width="727" alt="Screen Shot 2020-05-05 at 10 14 33 am" src="https://user-images.githubusercontent.com/29667122/81025221-4707aa00-8eb9-11ea-9f71-3806013f883f.png">

the expected behaviour (screenshot from local server response)
<img width="725" alt="Screen Shot 2020-05-04 at 1 55 54 pm" src="https://user-images.githubusercontent.com/29667122/81025322-afef2200-8eb9-11ea-859d-7015def9809b.png">

**Desktop (please complete the following information):**
 - OS: IOS Mojave 10.14.6
 - Browser: Safari
 - Version??

**Additional context**
This issue was discussed in Zulip [here](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/Testing/near/196193846).

This issue also might be related to issue #279 with[ PR#541](https://github.com/anitab-org/mentorship-backend/pull/541)

**Comment by mtreacy002** [comment] 2020-05-05 00:25
@isabelcosta, I'm not sure if just anyone can work on this issue, because the code change needs to be tested on dev server (which means after the code change got merged). Will you be ok if this PR is assigned to you? Alternatively, we can assume the issue is related to #279 which hopefully after the PR is approved and merged, the issue should disappear 😉

**Comment by isabelcosta** [comment] 2020-05-05 21:56
@mtreacy002 No problem in getting this assigned to me. However, I am pretty sure that this is solved with some pagination, it's not scalable to fetch every user (e.g.: 200+) in the database whenever a client (e.g.: Android app, Swagger UI) calls that endpoint.

For reference, here are the Heroku logs I shared on Zulip:

![image](https://user-images.githubusercontent.com/11148726/81119676-2d02b180-8f23-11ea-97f6-272c3ee4897d.png)

I am suggesting that this gets solved with pagination, also because I tested, with a search query to reduce the results and got a correct response. So it seems this can be the server taking to long to fetch every entry in the User table. So once PR #541 regarding Pagination is merged, this might get mitigated a bit. I will label the PR as of High priority.

**Comment by Abdelaty** [comment] 2020-08-07 20:24
Any updates here? Because this issue is a blocker for `[Members Search does not work anitab-org/mentorship-android#633]` (https://github.com/anitab-org/mentorship-android/pull/633)

**Comment by surbhigoel191** [comment] 2021-01-11 18:17
I would like to work on this issue! @isabelcosta @mtreacy002

**Comment by isabelcosta** [comment] 2021-01-24 03:10
@surbhigoel191 have you confirmed that this bug is a bug. I seem to remember this as being a bug solved by https://github.com/anitab-org/mentorship-backend/pull/541. i may be confusing, but if you could check first if this is still valid that would be great :)

**Comment by surbhigoel191** [comment] 2021-02-05 18:33
> @surbhigoel191 have you confirmed that this bug is a bug. I seem to remember this as being a bug solved by #541. i may be confusing, but if you could check first if this is still valid that would be great :)

Sorry for the late reply.
Yes, you are right, it has been resolved. We can close this issue now.

**Comment by isabelcosta** [comment] 2021-02-06 15:08
Closing this issue, since it's not reproducible.

**Closed as completed by isabelcosta** 2021-02-06 15:08 UTC
Labels: Category: Coding, Type: Bug
