### ISSUE TITLE
Preferred Languages for communication for a user

### ISSUE THREAD

**Issue by pbgurav** [anitab-org/mentorship-backend#775] opened 2020-08-30 07:20 UTC
In many countries though  English is used as a general purpose  language for communication, it will help  users if they are able to communicate in their preferred language of communication. User can specify one or more languages for communication with the order of their preference.Based on this attribute a User now can search mentors by applying the language criteria for search. **Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vj-codes** [comment] 2020-08-31 20:03
@pbgurav please follow the issue template. After that your issue will be approved/reviewed.Thanks!

**Comment by pbgurav** [comment] 2020-09-01 08:40
Is your feature request related to a problem? Please describe.
In many countries though English is used as a general purpose language for communication, it will help users if they are able to communicate in their preferred language of communication. 



Describe the solution you'd like.....
User can specify one or more languages for communication with the order of their preference.Based on this attribute a User now can search mentors by applying the language criteria for search.

**Comment by pbgurav** [comment] 2020-09-01 08:41
> @pbgurav please follow the issue template. After that your issue will be approved/reviewed.Thanks!

Done

**Comment by vj-codes** [comment] 2020-09-01 08:53
@pbgurav Thanks for updating but I need to close this as there's another issue dealing with the same point created before yours.

**Comment by vj-codes** [comment] 2020-09-01 08:54
Closing since duplicate of #336

**Closed as completed by vj-codes** 2020-09-01 08:54 UTC
