### ISSUE TITLE
docs: Update environment variables declarations in documentation

### ISSUE THREAD

**Issue by sankha555** [anitab-org/mentorship-backend#965] opened 2021-01-12 05:23 UTC
**Describe the bug**

As a developer,
I would like to be able to install and repository on my local system. Using any development configuration other than "local", requires one to add a few more environment variables. One of them, the declaration of "MOCK_EMAIL" has a slight misprint, due to which newcomers might face problems in settings up the repo. The issue is that there is whitespace between "MOCK_EMAIL" ,  "=" and "True/False" in the documentation, which if included in the cli too, will produce an error. This small misprint can be quickly fixed and might help in saving a bit more debugging time for newcomers.

**To Reproduce**

1. Open up your CLI and ```cd``` into your fork of ```mentorship-backend``` repository 
2. Declare new environment variable as ```MOCK_EMAIL = True``` (please note the spaces in between)
3. Error from bash : ```-bash: export: `=': not a valid identifier```

**Expected behavior**
Removing the spaces from the declarations will resolve the issue and not return any errors, the env variable will be set.

**Screenshots**
![image](https://user-images.githubusercontent.com/54751139/104272747-d000c780-54c3-11eb-8720-43e809df2fbe.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.5 Mojave
 - Tested on Terminal

**Additional context**
This issue might seem a bit too trivial to raise, but I thought it might help newcomers in setting up the repo on their system. I will be eager to quickly make a patch for the issue and make the required changes in the docs.

**Comment by sankha555** [comment] 2021-01-12 05:24
@isabelcosta @vj-codes What do you think about this issue? If you think that this needs to be fixed, I would go ahead and create a PR to address the same. Eagerly awaiting your reviews. Thanks!

**Comment by vj-codes** [comment] 2021-01-12 20:19
@sankha555 hey nice catch here ! 
Was able to reproduce it on my side, another observation is that `set` which is used on Windows OS allows spaces ,but export doesn't and thus issue is valid :)
Since this is a relatively easy fix let's keep this open for newcomers only.
Thank you for creating the issue🎉 
![image](https://user-images.githubusercontent.com/60894542/104367749-41329000-5541-11eb-927d-e80c58875329.png)

**Comment by sankha555** [comment] 2021-01-13 04:48
Sure @vj-codes , this will be a good issue to get newcomers started. Thanks for your motivating words! 😄

**Comment by battuAshita** [comment] 2021-01-15 12:11
Hi @sankha555 I would like to work on this.
Do we have to check how this works on MacOS and Version 10.14.5 Mojave also?

**Comment by sankha555** [comment] 2021-01-15 13:29
@battuAshita hey thanks for your interest! However, I can't assign the issue to you as I am not authorized to do so. You can tag the maintainers for the same!

Yes, this change will mostly be required in ubuntu and macOS systems. The change should be same across all versions of macOS, so a change in any of the version should work fine :smile:. Do ask here if you need any further help!

**Comment by battuAshita** [comment] 2021-01-15 14:12
> @battuAshita hey thanks for your interest! However, I can't assign the issue to you as I am not authorized to do so. You can tag the maintainers for the same!
> 
> Yes, this change will mostly be required in ubuntu and macOS systems. The change should be same across all versions of macOS, so a change in any of the version should work fine . Do ask here if you need any further help!

Thank you @sankha555. Sure, will ask in case of further help.

**Comment by battuAshita** [comment] 2021-01-15 14:13
Hi @vj-codes I would like to work on this. Can this issue be assigned to me?

**Comment by vj-codes** [comment] 2021-01-15 14:55
Assigning you @battuAshita 
Happy documenting! 
Do remember to follow our commit message style guide :)

**Comment by battuAshita** [comment] 2021-01-15 16:35
@vj-codes I have raised a PR #974. Please review.

**Closed as completed** 2021-01-17 23:34 UTC
Labels: Category: Documentation/Training, First Timers Only
