### ISSUE TITLE
Ability to log-in through third party services and accounts such as Login w/ Google or Login w/ Github

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#778] opened 2020-08-30 12:37 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vj-codes** [comment] 2020-08-30 13:09
Closing since duplicate of #730

**Closed as completed by vj-codes** 2020-08-30 13:10 UTC
