### ISSUE TITLE
Create Quality Assurance table for Update Task API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#473] opened 2020-03-03 18:59 UTC
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table to the docs in the `/docs` folder.

### Update [Required]
- [ ] Add test cases for Update Task API

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by StergiosSozos** [comment] 2020-03-12 18:29
Hello, i'm interested in working on this issue. I am not experienced in test cases but I am willing to do my best and spend the time needed to solve this issue. I will do both the test cases and the quality table.

**Comment by isabelcosta** [comment] 2020-03-12 19:49
@StergiosSozos sure :) Do you feel you understand this issue description? What we want here is a table to be added regarding this specific API, to the [Quality Assurance Docs](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md) on `/docs` folder.
The format should be the same as the other tables in that Markdown file.

**Comment by StergiosSozos** [comment] 2020-03-13 15:43
@isabelcosta  Hello again and sorry for the late response. As i undestand i have to run the tests from https://github.com/anitab-org/mentorship-backend/tree/develop/tests/tasks and then create the table , just like the other tables in the folder you linked. The problem is i can't find a test for Update Task, so i understood that i also need to write the test (As mentioned in the required criteria). Any help is more than welcomed as i'm not familiar with the project yet!

**Comment by isabelcosta** [comment] 2020-03-13 23:09
@StergiosSozos oh, what I mean by "Add test cases for Update Task API", is not to write test cases, in fact this is just about understanding what are some test scenarios you could evaluate either manually, or writing tests, that would fail or be successful. So you don't need to understand the code to write code, but to understand the logic and what are some general scenarios you could add to the Markdown table. So in this issue, you should only change the markdown file inside the `/docs` folder.

Also since you notice that some tests are missing for Update Task, you could also create an issue for it ;) Would you do that?

**Comment by StergiosSozos** [comment] 2020-03-14 15:25
@isabelcosta Okay now i undestand better what's needed. So i can try this issue (I'm aldready assinged to this one so no more actions needed)
I will also create the issue fot the missing Update task.

**Comment by StergiosSozos** [comment] 2020-03-16 18:56
@isabelcosta I started working on this issue, and I realised that the "Update task" is actually "complete task"
Please confirm this, so i can continue working on this, and also close the issue I opened #497 (as the complete task test exists.

**Comment by StergiosSozos** [comment] 2020-03-18 17:07
@isabelcosta when you have some time please check my previous question, thank you

**Comment by StergiosSozos** [comment] 2020-03-28 18:14
@isabelcosta I have submitted a PR for this issue. 
Please check my comments above too.

**Comment by isabelcosta** [comment] 2020-03-29 17:59
@StergiosSozos will look as soon as I can. I have been busy reviewing GSoC proposals.

**Closed as completed** 2020-05-08 14:42 UTC
Labels: Category: Documentation/Training, First Timers Only
