### ISSUE TITLE
TypeError: required field "type_ignores" missing from Module

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#746] opened 2020-08-24 13:04 UTC
**Describe the bug**

After setting up the project and running the command `python run.py` I encountered the following issue:-
```
TypeError: required field "type_ignores" missing from Module
```
**To Reproduce**

1. If you have a virtualenv folder then delete it and recreate the virtual environment as specified in the docs
2. Activate the virtual environment
3. Run `pip install -r requirements.txt` command.
4. Run `python run.py` command.
5. See the error.

**Expected behavior**

No error should be raised while running the project.

**Screenshots**

![image](https://user-images.githubusercontent.com/42068010/91047436-af7cc180-e637-11ea-9760-1afb6e52e85c.png)

**Additional context**

Refer this [link](https://github.com/pyeve/eve/issues/1331) to learn more about this issue.

**Comment by alapan-sau** [comment] 2020-08-24 19:51
Hey, I think I got the solution to this issue. The package Werkzeug==0.15.3 in the requirements.txt doesnt work properly with python3.8 . However with Werkzeug==1.0.1 (latest version) the problem is solved. Can I be assigned to this issue?

**Comment by PrashanthPuneriya** [comment] 2020-08-24 20:21
Great job! @alapan-sau. But, this issue is reserved for Open Source Hack (OSH) participants. If you are participating in it then for sure I will assign you this issue. Please free to check out other issues in the meantime :)

**Comment by alapan-sau** [comment] 2020-08-24 20:24
I would like to participate when it starts. Thanks!

**Comment by BALaka-18** [comment] 2020-08-24 21:39
Hi @PrashanthPuneriya, I am participating in Open Source Hack (OSH). Can I work on this issue ?

**Comment by PrashanthPuneriya** [comment] 2020-08-25 08:33
@alapan-sau I am assigning this issue to you since, you are participating in OSH and grabbed it first. But, remember that the PR for OSH will be valid only if you raised it during the OSH timeline.

**Comment by Abjcodes** [comment] 2020-08-31 18:33
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by alapan-sau** [comment] 2020-08-31 18:46
I am already assigned to it. I was waiting for the OSH to begin. I will send the PR by tomorrow.

**Comment by alapan-sau** [comment] 2020-08-31 20:05
<img width="1440" alt="Screenshot 2020-09-01 at 1 29 21 AM" src="https://user-images.githubusercontent.com/59991742/91762198-e1bb8f80-ebf2-11ea-9b47-29924434591e.png">
<img width="1440" alt="Screenshot 2020-09-01 at 1 27 40 AM" src="https://user-images.githubusercontent.com/59991742/91762391-ed0ebb00-ebf2-11ea-9bcf-c0a619f2a2c7.png">

Hey, After updating Werkzeug==0.15.3 to Werkzeug==1.0.1 the run.py started running as python3.8 is compatible with Werkzeug==1.0.1(latest) only. However, the tests are not passing. All 48 errors encountered at tests are caused by the same update in the module. The screenshots are provided. I think there is some backward compatibility issue with Werkzeug in testing.

**Comment by PrashanthPuneriya** [comment] 2020-09-01 07:53
@alapan-sau Hey, nice catch @alapan-sau! I googled on this issue and came across [this issue](https://github.com/jarus/flask-testing/issues/143). Can you learn more about this and conclude?
Apparently, Werkzeug 0.15.3 gives `type_ignores` issue and 1.0.1 gives `cached_property` issue. As mentioned in the link above they told 0.16.1 works fine and it is working for me. Can you also please test it?

**Comment by PrashanthPuneriya** [comment] 2020-09-04 15:24
@alapan-sau Its been three days. Any update on the PR? If you're not available to work on this issue then please inform so that I can assign this issue to others.

**Comment by alapan-sau** [comment] 2020-09-04 15:29
I am working. .I was busy for last 2 days..Will send a PR soon. Hopefully by tommorow

**Comment by PrashanthPuneriya** [comment] 2020-09-04 16:25
No worries @alapan-sau! Make sure that you update the progress every 3 days.

**Comment by PrashanthPuneriya** [comment] 2020-09-07 08:41
Are you still working on this issue @alapan-sau ? Or should I assign someone else?

**Comment by alapan-sau** [comment] 2020-09-07 09:20
No no..I read the issues on Werkzeug. I got the solution is using 0.16...But i was trying to figure out any work around for using the latest version.

**Comment by khushishikhu** [comment] 2020-09-08 05:54
@PrashanthPuneriya  may i take this issue

**Closed as completed** 2020-09-12 22:28 UTC
Labels: Category: Quality Assurance, Type: Bug, First Timers Only
