### ISSUE TITLE
fix: Swagger documentation HTTP code display

### ISSUE THREAD

**Issue by RiddhiAthreya** [anitab-org/mentorship-backend#1128] opened 2021-06-27 08:55 UTC
### Describe the bug
In some places in the swagger documentation, the HTTP error codes values aren't being displayed and instead the variables are being displayed.

### To Reproduce
1. Go to [https://mentorship-backend-temp.herokuapp.com/](https://mentorship-backend-temp.herokuapp.com/) and check under Mentorship Relation. This is just an example. There are many such instances across the project.

### Expected behavior
The error codes need to be displayed. Ex : 400 , 403 etc instead of HTTPStatus.NOT_FOUND

### Screenshots

![Screenshot (174)](https://user-images.githubusercontent.com/54843776/123538570-3f593380-d753-11eb-98c2-5b79e2cb78a9.png)

### Desktop:
 - OS: [Windows]
 - Browser [ chrome]

**Comment by RiddhiAthreya** [comment] 2021-06-27 08:59
@isabelcosta Can I work on this?

**Comment by epicadk** [comment] 2021-06-27 15:47
Yeah for some reason I think that's by design. Also maybe we could display the status code along with the status. 

For example 

**418** I'm a Teapot

cc @isabelcosta @anitab-org/mentorship-maintainers

**Comment by vj-codes** [comment] 2021-06-27 18:44
Duplicate of #939 but as it still exists you can work on this @RiddhiAthreya and thank you for reporting it :)

**Closed as completed** 2021-07-10 11:16 UTC
Labels: Category: Documentation/Training
