### ISSUE TITLE
Create [Update task] Test 

### ISSUE THREAD

**Issue by StergiosSozos** [anitab-org/mentorship-backend#497] opened 2020-03-15 18:01 UTC
## Description
The update task procedure is missing a test case. The test should be added in the task folder: (https://github.com/anitab-org/mentorship-backend/tree/develop/tests/tasks) 

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
[Cannot estimate] hours

**Comment by isabelcosta** [comment] 2020-04-05 19:51
@StergiosSozos can you please say in the issue description which test case is missing exactly, so that a contributor can solve this issue?

**Comment by StergiosSozos** [comment] 2020-04-07 11:29
> @StergiosSozos can you please say in the issue description which test case is missing exactly, so that a contributor can solve this issue?

I think it was a misunderstanding. The procedure "Update task" is also reffered as "Complete task"
So there is a test about "complete task", but in other places (for example #473) it is reffered as "update task"
I hope you undestand what I'm trying to say.

**Comment by ashokrayal** [comment] 2020-09-12 12:25
Hi @StergiosSozos , @isabelcosta,
Is this issue still open? I think we should close it.

**Comment by vj-codes** [comment] 2021-03-09 07:16
Closing as the issue is not valid , the test case is present in test_api_complete_task.py

**Closed as completed by vj-codes** 2021-03-09 07:16 UTC
Labels: Category: Quality Assurance, Type: Testing
