### ISSUE TITLE
sending request  for mentorship relation with incorrect end date, an appropriate error message is generated.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#617] opened 2020-05-29 10:03 UTC
When we send request for mentorship relation, an appropriate error message is generated.

**To Reproduce**

1. Go to 'Mentorship relation- send request'.
2. Provide authorization access token.
3. {
  "mentor_id": "271",
  "mentee_id": "272",
  "end_date": 11598400000,
  "notes": "string"
}
4. Click on 'Execute'.
5. Scroll down to 'Responses'.
6. 
![Screenshot (118)](https://user-images.githubusercontent.com/50888936/83247342-056cd500-a1c1-11ea-9816-13a09233abc6.png)

**Expected behavior**
It should have been "Invalid input for end date." and should be listed under responses.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser  chrome

**Comment by rpattath** [comment] 2020-05-29 21:15
Closing the issue because this is not an issue and it is an expected behavior.

**Closed as completed** 2020-05-29 21:14 UTC
