### ISSUE TITLE
Duplicate fields is_done and completed_at in GET /tasks

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#376] opened 2020-01-04 10:33 UTC
**Is your feature request related to a problem? Please describe.**
Use of both fields is unnecessary. **is_done** field can be removed.

**Describe the solution you'd like**
If **completed_at** has *null" value then it automatically implies that is_done is false. If **completed_at** contains a timestamp then task is complete.

```json
[
  {
    "id": 2,
    "description": "task2",
    "is_done": true,
    "created_at": 1577709722.596752,
    "completed_at": 1578133696.121925
  },
  {
    "id": 3,
    "description": "task3",
    "is_done": false,
    "created_at": 1577709726.626315,
    "completed_at": null
  }
]
```
**Describe alternatives you've considered**
Keep the API as it is. It doesn't obstruct functionality although it is unnecessary.

**Additional context**
None

**Comment by bartekpacia** [comment] 2020-01-04 15:28
I'll just add that there's more redundancy in `users` table, e.g `is_email_verified` and `email_verification_date`, you may want to create separate issues for those

**Comment by sankha555** [comment] 2020-05-06 05:33
Hello @daksha-aeer and @bartekpacia,
I am interested in working on this issue. If it's still under consideration, can you please assign it to me? Thanks!

**Comment by ashokrayal** [comment] 2020-09-12 12:28
Hi @PrashanthPuneriya, @daksha-aeer , 

Can you assigned this to me? I have no current issue in progress. 

Thanks

**Comment by PrashanthPuneriya** [comment] 2020-09-13 13:25
Go ahead! @Ashokrayal

**Comment by ashokrayal** [comment] 2020-09-24 03:42
Hi @PrashanthPuneriya,

The issue is not as simple as it looks. It can have many breaking changes and it will require complete API testing and it's also not that important. Someone very experienced on this project should pick this one or we can even ignore it.

**Comment by saikirankv** [comment] 2020-09-29 06:47
@PrashanthPuneriya @SanketDG  I would like to work on this. Can you assign this to me?

**Comment by PrashanthPuneriya** [comment] 2020-09-29 06:49
Assigned you @saikirankv

**Closed as completed** 2021-04-17 14:18 UTC
Labels: Category: Outreach/Research, Type: Bug
