### ISSUE TITLE
Design a solution for integrating third party apps authentication.

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#761] opened 2020-08-27 14:33 UTC
## Description
As a contributor, I need you to design a probable solution for integrating third-party apps authentication.
So that end-user can log in from other social media platforms and third-party apps.

Design a probable solution for integrating third-party apps authentication in the app and submit as a markdown file under the “docs” folder.

#### Important: The solution must be designed from the backend point of view and you need to make sure it is compatible with the current backend. This ONLY involves designing including code snippets (optional), not hardcore coding.
For context: #719 

#### Note: This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime. Program website: https://anitab-org.github.io/events/open-source-hack/

### Update [Required]
- [ ] Submit as a markdown file under the “docs” folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
[4+] hours

**Comment by gitpurva** [comment] 2020-08-31 20:10
I would like to work on this. Can you assign me this issue?

**Comment by paritoshsinghrahar** [comment] 2020-09-01 10:14
@gitpurva You both have been assigned other issues. Check back when you are done with that.

**Comment by titiksha01** [comment] 2020-09-01 22:25
@paritoshsinghrahar Hello, I want to work on this issue as a part of OSH, Can this be assigned to me?

**Comment by rishika1802** [comment] 2020-09-02 07:44
Hello I want to work on this issue as a apart of OSH will I be guided ?

**Comment by Aditiwebd** [comment] 2020-09-03 06:54
I want to work on this issue.Please assign it to me.

**Comment by vj-codes** [comment] 2020-09-03 07:52
@paritoshsinghrahar #719 is PR dealing with same issue.

**Comment by AprameyaGupta** [comment] 2020-09-03 09:09
@paritoshsinghrahar I would like to contribute in this as a part of OSH. Can you assign this issue to me?

**Comment by paritoshsinghrahar** [comment] 2020-09-03 11:04
@vj-codes It's been discussed in the comments. It's been approved. This issue is to suggest more uniform issue. Therefore for context, this has been mentioned in Issue description itself.

It can be found here: https://github.com/anitab-org/mentorship-backend/pull/719#issuecomment-680843392

> Such that someone might propose a probable uniform solution integrating more social logins like Slack, Facebook, Twitter, etc.
The proposal is only for suggestions/probable framework. Not involving coding.

**Comment by vj-codes** [comment] 2020-09-03 11:12
@paritoshsinghrahar If it's still available I would like to work on it:)

**Comment by paritoshsinghrahar** [comment] 2020-09-03 11:12
@rishika1802 Yes, you will be guided. I am assigning this issue to you. The whole idea is to help new contributors get started in Open Sorce programming.

First, you need to do the setup found here: https://github.com/anitab-org/mentorship-backend in README.
Then, you can proceed further. If this seems intimidating to you you can search for issues for `First Timers Only`.

Do tell me if you want to switch to something else. In that case, I might assign it to someone else.

**Comment by paritoshsinghrahar** [comment] 2020-09-03 11:20
@vj-codes I appreciate your enthusiasm but it's a First to Come First to get Served basis.
And same to others too. @Aditiwebd @AprameyaGupta @rishika1802.

**Comment by paritoshsinghrahar** [comment] 2020-09-03 11:23
@titiksha01 
I am assigning this to you for now. Happy Coding.  :smiley:

**Comment by paritoshsinghrahar** [comment] 2020-09-03 11:23
@rishika1802 Yes, you will be guided. The whole point is to get new contributors to get started in Open Souce.

First, Install the setup from https://github.com/anitab-org/mentorship-backend README file.
If this seems intimidating you can switch to issues labeled `First Timers Only`. Happy Coding.  :smiley:

**Comment by titiksha01** [comment] 2020-09-04 20:54
> @titiksha01
> I am assigning this to you for now. Happy Coding. 😃

@paritoshsinghrahar Thank you so much for this opportunity :)

**Comment by titiksha01** [comment] 2020-09-07 21:53
@paritoshsinghrahar Just wanted to confirm if i have understood the problem and have been researching correctly. The report i need to submit should contain a solution for integrating 3rd party apps,an idea of how to do so, its feasibility and compatibility with the back-end and which 3rd party apps/ social platforms it can integrate?

**Comment by paritoshsinghrahar** [comment] 2020-09-08 12:00
> @paritoshsinghrahar Just wanted to confirm if i have understood the problem and have been researching correctly. The report i need to submit should contain a solution for integrating 3rd party apps,an idea of how to do so, its feasibility and compatibility with the back-end and which 3rd party apps/ social platforms it can integrate?

@titiksha01  Yes, precisely.

**Comment by abhinav72610** [comment] 2020-09-11 04:55
@paritoshsinghrahar letme know if i can work on this with permission of @titiksha01

**Comment by titiksha01** [comment] 2020-09-11 05:25
@paritoshsinghrahar I am researching more about it currently. I had really hectic week, will submit the pr with documentation in 3-4 days...

**Comment by vj-codes** [comment] 2020-09-11 06:54
@titiksha01 If it's taking long , please do update after every 3 days as per the community guidelines

**Comment by vj-codes** [comment] 2020-09-11 06:57
@paritoshsinghrahar For this issue , there can be multiple solutions for integrating apps, some might come up with a shorter and simple one and some might have a longer one 
So I would suggest assigning 3ppl max for this issue and whatever PR is best will be implemented later.What say?

**Comment by vj-codes** [comment] 2020-09-11 06:58
then it can be assigned to @abhinav72610 after your confirmation since you created the issue

**Comment by pallavisavant** [comment] 2020-09-11 07:12
If available I would also like to take this up ....thanks.

**Comment by khushishikhu** [comment] 2020-09-11 12:08
may i take this issue

**Comment by titiksha01** [comment] 2020-09-14 14:44
@paritoshsinghrahar I researched about it and came across multiple solutions. I wanted to ask that the process i describe in my report should be specific to heruko app right?  
Also, like if for social media handles I find another approach apart from the one i had been primarily researching about so i can include that as well in the report?

**Comment by paritoshsinghrahar** [comment] 2020-09-15 23:07
> @paritoshsinghrahar I researched about it and came across multiple solutions. I wanted to ask that the process i describe in my report should be specific to heruko app right?

Umm, I hope you know Heroku app you talk about only is an online version of the backend REST APIs framework.
It can be set up on the local system. But yes it's how the backend works. It needs to be related/focused to that.

> Also, like if for social media handles I find another approach apart from the one i had been primarily researching about so i can include that as well in the report?

Yes.  You can.

**Comment by paritoshsinghrahar** [comment] 2020-09-15 23:11
@vj-codes I don't have any problem at all. It's just that the person who is assigned gets discouraged to contribute. Especially new contributors. So given its targetted for OSH, I wouldn't but any other issues I'll be fine with.

**Comment by ankit-saraf** [comment] 2020-09-17 08:40
@paritoshsinghrahar I would like to work on it if available

**Comment by arkumari2000** [comment] 2020-09-17 20:46
Can I work on this issue if it's available @paritoshsinghrahar ?

**Comment by titiksha01** [comment] 2020-09-17 22:21
@paritoshsinghrahar Please review my pr and suggest the necessary changes. This is my first pr for research so please guide me if I am going in the right direction in my research?

**Comment by vj-codes** [comment] 2021-03-09 06:57
Closing as duplicate of #341

**Closed as completed by vj-codes** 2021-03-09 06:57 UTC
Labels: Category: Outreach/Research, Status: Available
