### ISSUE TITLE
Create the greeting.yml file for the Welcome Bot

### ISSUE THREAD

**Issue by Aayush-hub** [anitab-org/mentorship-backend#1037] opened 2021-03-06 09:26 UTC
### Is your feature request related to a problem? Please describe.
The first time contributors should be greeted by a welcome message and link to code of conduct and contribution guidelines, so that they can follow them.

### Example:
![1](https://user-images.githubusercontent.com/65889104/110202009-18b57b00-7e8c-11eb-8617-3916a58ac023.png)

**Comment by epicadk** [comment] 2021-03-06 09:31
Duplicate of https://github.com/anitab-org/mentorship-backend/issues/717.

**Closed as completed** 2021-03-06 09:32 UTC
