### ISSUE TITLE
Sign in attempt blocked by Google while using Gmail to send verification emails

### ISSUE THREAD

**Issue by ashar-7** [anitab-org/mentorship-backend#233] opened 2019-11-30 15:04 UTC
**Describe the bug**
Google doesn't allow sign from the app for sending verification emails due to "less secure sign-in technology".

**Solution**
Turning on [less secure apps access](https://myaccount.google.com/lesssecureapps) solves this issue. This problem may occur while using other email providers too. So it would be great to have some documentation to help new users.

**To Reproduce**
1. Use a Gmail account as the verification email sender (make sure [less secure apps access](https://myaccount.google.com/lesssecureapps) is turned off)
2. Register a new user (or resend a verification email) in the app
3. You'll get an internal server error response in the app and a critical security alert in Gmail.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/26629623/69902084-80d70080-13af-11ea-9794-fdb63e8ba72d.jpg)

**Comment by sara-02** [comment] 2019-12-02 08:40
Just adding a note, this option to turn on the `less secure apps` is not available if you have enabled 2-step verification on Google. So one will have to disbale that first and then enbale the `less secure app` feature.

Quick update: Had to generate and add app password as a workaround.

**Comment by sara-02** [comment] 2019-12-02 20:00
Should get fixed by documenting a temporary email via this issue: https://github.com/systers/mentorship-backend/issues/233

**Comment by isabelcosta** [comment] 2020-02-22 22:16
we should document this in a markdown file I think 🤔 and then also have this in the Wiki, for troubleshooting purposes

**Comment by sumit-badsara** [comment] 2020-02-23 12:19
@isabelcosta @sara-02 We also have another another option which is much better and safer.

We can just go to Gmail and enable **2 step verification**, and then go to **App Passwords** and **generate a password** for **Mail** app. Using that, even your email is secure and you don't need to configure anything else.

Reference : https://support.google.com/accounts/answer/185833?hl=en

I can create a PR regrading that in case you need it (We can add that in readme I guess :thinking: )

**Comment by sara-02** [comment] 2020-02-24 09:31
@BadduCoder I did the same. But something did not work, I finally had to switch off the 2 step Auth.
Do look into it and see if these steps work as expected.

**Comment by sumit-badsara** [comment] 2020-02-25 21:37
@sara-02 could you tell me what error are you getting and what steps have you followed ?

**Comment by mtreacy002** [comment] 2020-02-27 23:32
> @BadduCoder I did the same. But something did not work, I finally had to switch off the 2 step Auth.
> Do look into it and see if these steps work as expected.

@sara-02, I came across this issue as well (issue #461) and found out that the problem lies with the 'Less secure app access" need to be 'ON'. I'm not sure if this is the same in your case, you might want to give it a try.

**Comment by mtreacy002** [comment] 2020-02-27 23:37
> @BadduCoder I did the same. But something did not work, I finally had to switch off the 2 step Auth.
> Do look into it and see if these steps work as expected.

@sara-02, I had this issue as well (#461) and switching 'OFF' 2 step verification and switch 'ON' Less secure app access fixed it for me. But I noticed you mentioned this already been done in your previous post.

**Comment by sumit-badsara** [comment] 2020-03-03 16:55
Ohkay!
@mtreacy002 just try this once and tell me if this works:
1. Go to https://myaccount.google.com/
2. Go to **Security**
3. Turn on **2-Step Verification**
4. Come back to **Settings**
5. Go to **App Passwords** 
6. **Generate** a new password (app: *Mail*, device:*Any*)
7. Copy that **password** and use it as password in .env file.

LESS SECURE APPS: **OFF**
2 FACTOR AUTH: **ON**

Just try this once and let me know the results.

**Comment by mtreacy002** [comment] 2020-03-04 05:12
Thanks, @BadduCoder. I gave it a try as you suggested above, and it works!! 👍.

**Comment by isabelcosta** [comment] 2020-03-04 22:40
@BadduCoder @mtreacy002 @sara-02 @ashar-7 I was thinking that there are some issues that could be documented in a doc as markdown file inside the docs folder. Something dedicated to troubleshooting some common problems developers face. I see this as one of them. I will create an issue for it.

**Comment by isabelcosta** [comment] 2020-03-09 22:53
OMG I just found another little step that made this go away at least for my Heroku deployment. Its here: https://www.twilio.com/blog/2018/03/send-email-programmatically-with-gmail-python-and-flask.html 🙌 

These 2 steps

![image](https://user-images.githubusercontent.com/11148726/76264132-c6318680-6258-11ea-88a6-33725a31ed11.png)

**Comment by isabelcosta** [comment] 2020-03-11 21:16
To fix the issue of the email internal server error, that i am getting from using a Gmail address to send email (caused by the security that Gmail provides), I will use another email.
I created a new email on https://www.mail.com/mail/

I am letting you know so you can also check this out for testing, I tested locally and so far, no issues. I will update the environment variables on Heroku app and hopefully this will be solved.
Here's the article I researched for Gmail alternatives: https://www.hongkiat.com/blog/gmail-alternatives/

Here's an example of how to set the env variables (if you are using https://www.mail.com/mail/):
```
MAIL_DEFAULT_SENDER=YOUR_MAIL_EMAIL
MAIL_SERVER='smtp.mail.com'
APP_MAIL_USERNAME='YOUR_MAIL_EMAIL'
APP_MAIL_PASSWORD='YOUR_MAIL_PASSWORD'
```

**Comment by mtreacy002** [comment] 2020-03-24 12:30
Hi @isabelcosta, just curious, I can't reproduce the same error (internal server error) that caused by this Gmail blocking. I now need it to be blocked to test my #463 PR 🤣. I've [posted](https://github.com/anitab-org/mentorship-backend/pull/463#issuecomment-603134878) a comment on that PR. And I also have pushed the changes requested by @ramitsawhney27 even though I couldn't test it coz that Gmail being so 'forgiving' to me... 😆.

**Comment by vj-codes** [comment] 2020-09-07 07:25
@ashar-7 @isabelcosta closing since this issue cannot be reproduced by other new contributors

**Closed as completed by vj-codes** 2020-09-07 07:25 UTC
Labels: Category: Documentation/Training
