### ISSUE TITLE
Create Quality Assurance table for Email Confirmation API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#471] opened 2020-03-03 18:56 UTC
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table to the docs in the `/docs` folder.

### Update [Required]
- [ ] Add test cases for Email Confirmation API

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by lorryaze** [comment] 2020-03-03 22:53
Can I try this?

**Comment by isabelcosta** [comment] 2020-03-03 23:12
@lorryaze thank you for your interest here. Because you already did a contribution to this project, it would be best to leave this to new contributors (because of the "First timers only" label). But if you have something in mind that could help the next contributor feel free to share it here.

**Comment by isabelcosta** [comment] 2020-03-04 13:21
@lorryaze I thought about this, I think it would be useful to have a first example of how this type of documentation contribution would work, and serve as an example for future contributors. So i removed the first timers only label. Do you still want to contribute to this? Feel free to do so and ask any questions you might have about how to come up with such example :)

**Comment by lorryaze** [comment] 2020-03-05 03:02
> @lorryaze I thought about this, I think it would be useful to have a first example of how this type of documentation contribution would work, and serve as an example for future contributors. So i removed the first timers only label. Do you still want to contribute to this? Feel free to do so and ask any questions you might have about how to come up with such example :)

Yes I will try work on this, I sorry for the delay.

**Comment by isabelcosta** [comment] 2020-03-05 19:17
no worries at all @lorryaze :)

**Comment by lorryaze** [comment] 2020-03-10 15:58
@isabelcosta can you explain me how the table should look? I alredy identifed the test cases.

**Comment by isabelcosta** [comment] 2020-03-10 21:52
That is great 👏 It could be similar to the other tables that are in the quality assurance docs. So it should follow this structure: https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#revoke-an-admin-role @lorryaze

**Comment by vj-codes** [comment] 2020-08-24 12:31
Unassigning @lorryaze due to inactivity.

**Comment by paritoshsinghrahar** [comment] 2020-08-26 18:19
@isabelcosta Should I add Open Source Hack Label to this?

**Comment by isabelcosta** [comment] 2020-09-05 00:27
@paritoshsinghrahar sure :) I am fine with it!

**Comment by pallavisavant** [comment] 2020-09-06 11:21
I have participated for OSH....if this is still available can i take up this one... as i haven't been assigned any under documentation...Thanks.

**Comment by paritoshsinghrahar** [comment] 2020-09-08 12:04
@pallavisavant Sure. I am assigning this to you.

**Comment by pallavisavant** [comment] 2020-09-08 13:58
@paritoshsinghrahar i have the TC ready..i wanted to test them all...but like after me registering new user ,we get a verification mail post clicking gets the user account confirmed...now how do we get the token on registered email to enter it during email confirmation....Thanks.

**Comment by pallavisavant** [comment] 2020-09-08 19:54
@paritoshsinghrahar this is my first PR...pls do review and let me know if any changes required....Thanks.

**Comment by paritoshsinghrahar** [comment] 2020-09-09 16:49
@pallavisavant Sure. You can continue on to other issues.

**Closed as completed** 2020-09-12 23:29 UTC
Labels: Category: Documentation/Training, Status: Available, Type: Enhancement
