### ISSUE TITLE
Chore: Use `--no-cache-dir` flag to `pip` in Dockerfiles, to save space

### ISSUE THREAD

**Issue by rajpratik71** [anitab-org/mentorship-backend#737] opened 2020-08-21 03:43 UTC
Using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.

Further , more detail information can be found at

https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6

**Comment by rajpratik71** [comment] 2020-08-21 03:46
This issue is discussion thread for already raised pull request #735

**Comment by isabelcosta** [comment] 2020-08-23 16:44
@Rajpratik71 could you follow one of our templates? In this case would be the "User story" template, which you can find in `.github` folder.

I can assign this to you now that I understand and see that the issue is valid.

**Closed as completed** 2020-08-28 22:17 UTC
Labels: Category: Coding, Type: Maintenance
