### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by CleverFool77** [anitab-org/mentorship-backend#199] opened 2019-02-21 08:03 UTC
**Describe the bug**
There are 12 errors while running the unittests in terminal using the command `python -m unittest discover tests`

Below is this traceback
```bash
(venv) lekhika@lekhika:~/github/mentorship-backend$ python -m unittest discover tests
.......EEEEEEEEEEEE...............................................................................................................................................................
======================================================================
ERROR: test_accept_mentorship_request (mentorship_relation.test_api_accept_request.TestAcceptMentorshipRequestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_accept_request.py", line 48, in test_accept_mentorship_request
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test__mentee_cancel_mentorship_relation (mentorship_relation.test_api_cancel_relation.TestCancelMentorshipRelationApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_cancel_relation.py", line 63, in test__mentee_cancel_mentorship_relation
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test__mentor_cancel_mentorship_relation (mentorship_relation.test_api_cancel_relation.TestCancelMentorshipRelationApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_cancel_relation.py", line 52, in test__mentor_cancel_mentorship_relation
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_receiver_delete_mentorship_request (mentorship_relation.test_api_delete_request.TestDeleteMentorshipRequestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_delete_request.py", line 69, in test_receiver_delete_mentorship_request
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_sender_delete_mentorship_request (mentorship_relation.test_api_delete_request.TestDeleteMentorshipRequestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_delete_request.py", line 54, in test_sender_delete_mentorship_request
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_all_mentorship_relations (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 113, in test_list_all_mentorship_relations
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_current_mentorship_relation (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 104, in test_list_current_mentorship_relation
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_current_mentorship_relation_sent_by_another_user (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 132, in test_list_current_mentorship_relation_sent_by_another_user
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_current_mentorship_relation_sent_by_current_user (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 122, in test_list_current_mentorship_relation_sent_by_current_user
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_past_mentorship_relations (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 86, in test_list_past_mentorship_relations
    self.assertEqual([marshal(self.past_mentorship_relation, mentorship_request_response_body)], json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_list_pending_mentorship_relations (mentorship_relation.test_api_list_relations.TestListMentorshipRelationsApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_list_relations.py", line 95, in test_list_pending_mentorship_relations
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: test_reject_mentorship_request (mentorship_relation.test_api_reject_request.TestRejectMentorshipRequestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lekhika/github/mentorship-backend/tests/mentorship_relation/test_api_reject_request.py", line 51, in test_reject_mentorship_request
    json.loads(response.data))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

----------------------------------------------------------------------
Ran 178 tests in 28.028s

FAILED (errors=12)
```

**To Reproduce**
1. Run the command `python -m unittest discover tests`

**Expected behavior**
There should be no error.

**Comment by isabelcosta** [comment] 2019-03-27 23:17
@CleverFool77 just saw this now, is this still a problem??

**Comment by CleverFool77** [comment] 2019-04-02 03:35
I didn't try it right now, I'll fetch the latest changes and will checkout in afternoon.

**Comment by CleverFool77** [comment] 2019-04-03 03:56
Hi @isabelcosta I tried it. The errors are still there.

**Comment by Anjalizi** [comment] 2019-11-16 15:48
Initially I got a couple of errors but on running `pip3 install flask_testing` the errors go.

**Comment by sara-02** [comment] 2019-12-02 06:54
@CleverFool77 Which version of Python3 are you using?  For Python 3.6+ this should be fixed.

**Comment by sara-02** [comment] 2019-12-02 07:01
@isabelcosta @CleverFool77 I just tested this with `Python3.5` and can confirm the errors reported above.
Steps to reproduce(if you have Python3.5 or any lower version of Python3)
```bash
virtualenv venv3 --python=python3.5
source venv3/bin/activate
pip3 install -r requirements.txt
python3 -m unittest discover tests.
```
```python
----------------------------------------------------------------------
Ran 187 tests in 26.230s

FAILED (failures=2, errors=12)

```

Maybe we should add it in the README.md to use 3.6+

Ref: https://docs.python.org/3/whatsnew/3.6.html#json

**Comment by mtreacy002** [comment] 2019-12-16 09:01
@isabelcosta, is this still an issue to anyone? I tried running the test just now (on python3.7) and it works just fine.

<img width="878" alt="Screen Shot 2019-12-16 at 7 56 04 pm" src="https://user-images.githubusercontent.com/29667122/70892988-4a9bb100-203e-11ea-93d3-112d85b3fe88.png">

btw, I'm using virtualenvwrapper. Maybe just as @Sara-02 says, it needs python 3.6+

**Comment by vj-codes** [comment] 2021-02-20 19:07
Closing since backend uses python 3.6+  and the issue occurs below that level

**Closed as completed by vj-codes** 2021-02-20 19:07 UTC
